<?
$PERM["forum"]["7"]="W";
$PERM["forum"]["6"]="W";
$PERM["blogs"]["7"]="W";
$PERM["blogs"]["6"]="W";
$PERM["news"]["7"]="W";
$PERM["news"]["6"]="W";
$PERM["index.php"]["7"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>