<i title="Cash" class="cacsh"></i>
<i title="MasterCard" class="mastercard"></i>
<i title="Visa" class="visa"></i>
<i title="Sberbank" class="sbrf"></i>
<i title="Alfa" class="alfa"></i>
<i title="Mir" class="mir"></i>
<i title="Yoomoney" class="yoomoney"></i>
<i title="Halva" class="halva"></i>
<i title="Tinkoff" class="tinkoff"></i>