<?
if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true ) die();

global $arTheme;
$arParams = $arConfig['PARAMS'];

?>
<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section",
	$arParams['DISPLAY'],
	Array(
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"DETAIL_URL" => "",
		"FILTER_NAME" => $arParams['FILTER_NAME'],
		"HIT_PROP" => "HIT",
		"IBLOCK_TYPE" => "aspro_allcorp3_catalog",
		"IBLOCK_ID"	=> \Bitrix\Main\Config\Option::get('aspro.allcorp3', 'CATALOG_IBLOCK_ID', '50'),
		"PAGE_ELEMENT_COUNT" => $arParams['LINKED_CATALOG_COUNT'],
		"PROPERTY_CODE"	=> $arParams['LINKED_PROPERTY_CODE'] ?? $arParams['LIST_PROPERTY_CODE'] ?? $arParams['PROPERTY_CODE'],
		"ELEMENT_SORT_FIELD" => $arParams['ELEMENT_SORT_FIELD'],
		"ELEMENT_SORT_ORDER" => $arParams['ELEMENT_SORT_ORDER'],
		"ELEMENT_SORT_FIELD2" => "ID",
		"ELEMENT_SORT_ORDER2" => "DESC",
		//"SECTION_ID" => "",
		//"SECTION_CODE" => "",
		"FIELD_CODE" => $arParams['LINKED_FIELD_CODE'] ?? $arParams['LIST_FIELD_CODE'] ?? $arParams['FIELD_CODE'],
		"ELEMENTS_TABLE_TYPE_VIEW" => "FROM_MODULE",
		"SHOW_SECTION" => "Y",
		"COUNT_IN_LINE" => "",
		"LINE_ELEMENT_COUNT" => "",
		"SHOW_DISCOUNT_TIME" => $arParams["SHOW_DISCOUNT_TIME"],
		"SHOW_OLD_PRICE" => "Y",
		"SHOW_PREVIEW_TEXT" => "N",
		"SHOW_DISCOUNT_PRICE" => "Y",
		"SHOW_GALLERY" => $arTheme['SHOW_CATALOG_GALLERY_IN_LIST']['VALUE'],
		"MAX_GALLERY_ITEMS" => $arTheme['SHOW_CATALOG_GALLERY_IN_LIST']['DEPENDENT_PARAMS']['MAX_GALLERY_ITEMS']['VALUE'],
		"ADD_PICT_PROP" => \Bitrix\Main\Config\Option::get('aspro.allcorp3', 'GALLERY_PROPERTY_CODE', 'PHOTOS'),
		"DISPLAY_TOP_PAGER"	=>	"N",
		"DISPLAY_BOTTOM_PAGER"	=>	"Y",
		"PAGER_TITLE"	=>	"",
		"PAGER_TEMPLATE"	=>	".default",
		"PAGER_TEMPLATE"	=>	"main",
		"PAGER_SHOW_ALWAYS"	=>	"N",
		"PAGER_DESC_NUMBERING"	=>	"N",
		"PAGER_DESC_NUMBERING_CACHE_TIME"	=>	"36000",
		"PAGER_SHOW_ALL" => "N",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SECTION_COUNT_ELEMENTS" => $arParams["SECTION_COUNT_ELEMENTS"],
		"IS_CATALOG_PAGE" => 'Y',
		"META_KEYWORDS" => "",
		"META_DESCRIPTION" => "",
		"BROWSER_TITLE" => "",
		"ADD_SECTIONS_CHAIN" => "N",
		"DISPLAY_COMPARE" => CAllcorp3::GetFrontParametrValue('CATALOG_COMPARE'),

		"SHOW_ONE_CLICK_BUY" => CAllcorp3::GetFrontParametrValue('SHOW_ONE_CLICK_BUY'),
		"USE_FAST_VIEW_PAGE_DETAIL" => CAllcorp3::GetFrontParametrValue('USE_FAST_VIEW_PAGE_DETAIL'),
		"EXPRESSION_FOR_FAST_VIEW" => CAllcorp3::GetFrontParametrValue('EXPRESSION_FOR_FAST_VIEW'),
		"ORDER_VIEW" => CAllcorp3::GetFrontParametrValue('ORDER_VIEW'),

		"SHOW_DISCOUNT" => $arParams['SHOW_DISCOUNT'],
		"OPT_BUY" => $arParams['OPT_BUY'],

		"SKU_IBLOCK_ID"	=>	$arParams["SKU_IBLOCK_ID"],
		"SKU_TREE_PROPS"	=>	$arParams["SKU_TREE_PROPS"],
		"SKU_PROPERTY_CODE"	=>	$arParams["SKU_PROPERTY_CODE"],
		"SKU_SORT_FIELD" => $arParams["SKU_SORT_FIELD"],
		"SKU_SORT_ORDER" => $arParams["SKU_SORT_ORDER"],
		"SKU_SORT_FIELD2" => $arParams["SKU_SORT_FIELD2"],
		"SKU_SORT_ORDER2" =>$arParams["SKU_SORT_ORDER2"],

		"DOTS_0" => "Y",
		"DOTS_380" => "Y",
		"DOTS_768" => "Y",
		"DOTS_1200" => "Y",
		"ELEMENT_IN_ROW" => $arParams['ELEMENT_IN_ROW'] ?? 5,
		"ELEMENT_IN_ROW" => $arParams['LINE_TO_ROW']+1,
		"POSITION_BTNS" => "3",
		"AJAX_REQUEST" => $arParams['AJAX'],
		"TEXT_CENTER" => false,
		"IMG_CORNER" => false,
		"GRID_GAP" => "20",
		"ROW_VIEW" => true,
		"BORDER" => true,
		"ITEM_HOVER_SHADOW" => $arParams['ITEM_HOVER_SHADOW'],
		"DARK_HOVER" => false,
		"ROUNDED" => true,
		"ROUNDED_IMAGE" => true,
		"ITEM_PADDING" => true,
		"MAXWIDTH_WRAP" => false,
		"MOBILE_SCROLLED" => false,
		"NARROW" => "Y",
		"IS_CATALOG_PAGE" => "N",
		"ITEMS_OFFSET" => true,
		"IMAGES" => "PICTURE",
		"IMAGE_POSITION" => "LEFT",
		"SHOW_PREVIEW" => true,
		"SHOW_TITLE" => false,
		"TITLE_POSITION" => "",
		"TITLE" => "",
		"RIGHT_TITLE" => "",
		"RIGHT_LINK" => "",
		"POSITION_BTNS" => $arParams['LINE_TO_ROW'],
		"CHECK_REQUEST_BLOCK" => CAllcorp3::checkRequestBlock("goods-list-inner"),
		"IS_AJAX" => CAllcorp3::checkAjaxRequest(),
		"SHOW_PROPS" => CAllcorp3::GetFrontParametrValue('SHOW_PROPS_BLOCK'),
		"SHOW_PROPS_TABLE" => $arParams['SHOW_PROPS_TABLE'],
		"NAME_SIZE" => "18",
		"SUBTITLE" => "",
		"SHOW_PREVIEW_TEXT" => "N",
	),
	$component, array('HIDE_ICONS' => 'Y')
);?>