<?if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true ) die();?>
<?
global $arTheme, $APPLICATION;
$arParams = $arConfig['PARAMS'];

$bTariffsUseDetail = $arTheme['TARIFFS_USE_DETAIL']['VALUE'] === 'Y';
$tariffsDetailLinked = $arTheme['DETAIL_LINKED_TARIFFS']['VALUE'];

$blockTemplateOptions = $GLOBALS['arTheme']['DETAIL_LINKED_TARIFFS']['LIST'][$tariffsDetailLinked];
$bItemsOffset = $blockTemplateOptions['ADDITIONAL_OPTIONS']['LINKED_OFFSET_TARIFFS']['VALUE'] === 'Y';
$itemsImages = $tariffsDetailLinked=='type_1'?'BIG_PICTURES':$blockTemplateOptions['ADDITIONAL_OPTIONS']['LINKED_IMAGES_TARIFFS']['VALUE'];
?>

<?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"tariffs-list", 
	array(
		"IBLOCK_TYPE" => "aspro_allcorp3_catalog",
		"IBLOCK_ID" => "42",
		"NEWS_COUNT" => "20",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "DESC",
		"FILTER_NAME" => "arrTariffsFilter",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "FORM_ORDER",
			2 => "HIT",
			3 => "ONLY_ONE_PRICE",
			4 => "PRICE_CURRENCY",
			5 => "TARIF_PRICE_1",
			6 => "TARIF_PRICE_2",
			7 => "TARIF_PRICE_2_DISC",
			8 => "TARIF_PRICE_3",
			9 => "TARIF_PRICE_3_DISC",
			10 => "TARIF_PRICE_DEFAULT",
			11 => "TARIF_PRICE_DEFAULT_DISC",
			12 => "MULTI_PROP_BOTTOM_PROPS",
			13 => "MULTI_PROP",
			14 => "SUPPLIED",
			15 => "USERS",
			16 => "EXTENSION",
			17 => "DURATION",
			18 => "GROUPS_USERS",
			19 => "TASK",
			20 => "ADMIN",
			21 => "VOLUME",
			22 => "ONLINE",
			23 => "FILE_STORAGE",
			24 => "MESSAGE",
			25 => "MEMORY",
			26 => "CPU",
			27 => "IP",
			28 => "HOSTING_SITES",
			29 => "KOLLICHESTVO_BAZ_DANNIX",
			30 => "UPDATES",
			31 => "LANGUAGES",
			32 => "TARIF_PRICE_1_DISC",
			33 => "TARIF_PRICE_4",
			34 => "ICON",
			35 => "VISA",
			36 => "NUM_DEVICES",
			37 => "APPLE",
			38 => "ELPURSE",
			39 => "API_INTEGRATION",
			40 => "SIEM_SYSTEM",
			41 => "COLLECT_INFO",
			42 => "RULES_SIGNAT",
			43 => "SCANNER",
			44 => "ANTIVIRUS",
			45 => "PROTECT_PAYMENT",
			46 => "PROTECT_CAMERA",
			47 => "ANTIVOR",
			48 => "CONTROL",
			49 => "SUPPORT_FREE",
			50 => "GUARANTEE",
			51 => "BLOCKING_SITES",
			52 => "BLOCKING_TRAFFIC",
			53 => "SECURITY",
			54 => "PROTECT_CHILDREN",
			55 => "SUM_FINANCING",
			56 => "TERM_LEASING",
			57 => "INSURANCE",
			58 => "CURRENCY",
			59 => "ADVANCE_PAY",
			60 => "RATE",
			61 => "PERCENTAGE",
			62 => "PAYMENTS",
			63 => "SUPPORT",
			64 => "NOTIFICATION",
			65 => "TURN",
			66 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"PAGER_TEMPLATE" => "ajax",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"COMPONENT_TEMPLATE" => "tariffs-list",
		"SET_LAST_MODIFIED" => "N",
		"STRICT_SECTION_CHECK" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SHOW_DATE" => "N",
		"COUNT_IN_LINE" => "3",
		"USE_DETAIL" => $bTariffsUseDetail?"Y":"N",
		"VISIBLE_PROP_COUNT" => "4",
		"ROW_VIEW" => $tariffsDetailLinked=="type_3",
		"BORDER" => true,
		"ITEM_HOVER_SHADOW" => true,
		"DARK_HOVER" => false,
		"ROUNDED" => true,
		"ROUNDED_IMAGE" => $tariffsDetailLinked=="type_2"&&$itemsImages=="ROUND_IMAGES",
		"ELEMENTS_ROW" => $tariffsDetailLinked=="type_3"?"1":"3",
		"MAXWIDTH_WRAP" => false,
		"MOBILE_SCROLLED" => false,
		"HIDE_PAGINATION" => "N",
		"SLIDER" => $tariffsDetailLinked!=="type_3",
		"GRID_GAP" => $bItemsOffset?"0":"32",
		"DOTS_0" => "Y",
		"ITEM_0" => "1",
		"DOTS_380" => "Y",
		"ITEM_380" => "1",
		"DOTS_768" => "N",
		"ITEM_768" => "2",
		"DOTS_1200" => "N",
		"ITEM_1200" => "3",
		"VIEW_TYPE" => $tariffsDetailLinked,
		"ORDER_VIEW" => $bOrderViewBasket,
		"NARROW" => true,
		"ITEMS_OFFSET" => $bItemsOffset,
		"IMAGES" => $itemsImages,
		"HIDE_LEFT_TEXT_BLOCK" => "Y",
		"TABS" => "INSIDE",
		"DEFAULT_PRICE_KEY" => "",
		"SHOW_TITLE" => false,
		"TITLE_POSITION" => "",
		"TITLE" => "",
		"RIGHT_TITLE" => "",
		"RIGHT_LINK" => "",
		"CHECK_REQUEST_BLOCK" => CAllcorp3::checkRequestBlock("tariffs"),
		"IS_AJAX" => CAllcorp3::checkAjaxRequest(),
		"NAME_SIZE" => "18",
		"SUBTITLE" => "",
		"SHOW_PREVIEW_TEXT" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	false,
	array(
		"HIDE_ICONS" => "N"
	)
);?>